site_name: GEE Tools
repo_url: https://github.com/rogeralmengor/gee-tools

theme:
  name: readthedocs
  highlightjs: false

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: github-dark
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list

nav:
  - Home: index.md
  - Tools:
      - Generate Samples: tools/generate_samples.md
